// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddPath adds a folder or file to the protected list.
 * @param {string} path
 * @param {string} pin
 * @returns {$CancellablePromise<void>}
 */
export function AddPath(path, pin) {
    return $Call.ByID(2105985761, path, pin);
}

/**
 * CancelIPCAuth is called when the user dismisses the IPC auth dialog.
 * @returns {$CancellablePromise<void>}
 */
export function CancelIPCAuth() {
    return $Call.ByID(4237968635);
}

/**
 * CheckDiskSpace returns disk space info for a folder.
 * @param {string} path
 * @returns {$CancellablePromise<$models.DiskSpaceInfo>}
 */
export function CheckDiskSpace(path) {
    return $Call.ByID(3312650982, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.UpdateInfo>}
 */
export function CheckForUpdate() {
    return $Call.ByID(3363528925).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} path
 * @param {string} pin
 * @returns {$CancellablePromise<void>}
 */
export function DecryptLazyVault(path, pin) {
    return $Call.ByID(2435244966, path, pin);
}

/**
 * DetectDevice checks if a FIDO2 device is connected.
 * @returns {$CancellablePromise<boolean>}
 */
export function DetectDevice() {
    return $Call.ByID(948697146);
}

/**
 * EnterFullscreen switches the window to fullscreen for the lock screen.
 * If force authentication is enabled, activates kiosk mode.
 * @returns {$CancellablePromise<void>}
 */
export function EnterFullscreen() {
    return $Call.ByID(2510957186);
}

/**
 * ExitFullscreen switches the window to normal mode after unlock.
 * @returns {$CancellablePromise<void>}
 */
export function ExitFullscreen() {
    return $Call.ByID(4187733006);
}

/**
 * GetAdminGateCommand returns the terminal command the user should run to
 * install or remove the admin gate. Installs sudo PAM gate on all platforms
 * and the authorization plugin on macOS.
 * @param {string} mode
 * @returns {$CancellablePromise<string>}
 */
export function GetAdminGateCommand(mode) {
    return $Call.ByID(1430585252, mode);
}

/**
 * GetSettings returns settings from the secure config.
 * @returns {$CancellablePromise<$models.CombinedSettings>}
 */
export function GetSettings() {
    return $Call.ByID(3129821644).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetStatus returns the current app state.
 * @returns {$CancellablePromise<$models.AppStatus>}
 */
export function GetStatus() {
    return $Call.ByID(779018179).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1806113387);
}

/**
 * HandleIPCAuth is called by the frontend after the user enters their PIN.
 * @param {string} pin
 * @returns {$CancellablePromise<void>}
 */
export function HandleIPCAuth(pin) {
    return $Call.ByID(1932996403, pin);
}

/**
 * HideToTray hides the window back to the system tray.
 * If the app is locked with force auth, re-enters fullscreen instead.
 * @returns {$CancellablePromise<void>}
 */
export function HideToTray() {
    return $Call.ByID(4144683102);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsLocked() {
    return $Call.ByID(1474303637);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsRegistered() {
    return $Call.ByID(1771316975);
}

/**
 * ListKeys returns information about registered security keys.
 * @returns {$CancellablePromise<$models.KeyInfo[]>}
 */
export function ListKeys() {
    return $Call.ByID(257323087).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Lock encrypts all vaults and clears secrets from memory.
 * @returns {$CancellablePromise<void>}
 */
export function Lock() {
    return $Call.ByID(3911181120);
}

/**
 * LockVault re-encrypts a single vault on demand.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function LockVault(path) {
    return $Call.ByID(3409273988, path);
}

/**
 * Register creates a new FIDO2 credential and wraps the master secret with it.
 * If this is the first credential, generates the master secret and hmac salt.
 * If credentials already exist, wraps the existing master secret with the new key.
 * @param {string} pin
 * @param {string} label
 * @returns {$CancellablePromise<void>}
 */
export function Register(pin, label) {
    return $Call.ByID(2189947386, pin, label);
}

/**
 * RemoveFolder removes a folder from protection. Ensures files are decrypted first.
 * Requires FIDO2 re-auth.
 * @param {string} folderPath
 * @param {string} pin
 * @returns {$CancellablePromise<void>}
 */
export function RemoveFolder(folderPath, pin) {
    return $Call.ByID(205196671, folderPath, pin);
}

/**
 * RemoveKey removes a registered credential. Cannot remove the last key.
 * Requires FIDO2 re-auth.
 * @param {string} credentialID
 * @param {string} pin
 * @returns {$CancellablePromise<void>}
 */
export function RemoveKey(credentialID, pin) {
    return $Call.ByID(3195920610, credentialID, pin);
}

/**
 * ResizeWindow resizes the window to fit content.
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function ResizeWindow(width, height) {
    return $Call.ByID(1466929615, width, height);
}

/**
 * RevealSecureConfig opens the system file manager to the secure config directory.
 * @returns {$CancellablePromise<void>}
 */
export function RevealSecureConfig() {
    return $Call.ByID(204196149);
}

/**
 * @param {application$0.WebviewWindow | null} w
 * @returns {$CancellablePromise<void>}
 */
export function SetWindow(w) {
    return $Call.ByID(541633429, w);
}

/**
 * StartDeviceWatcher polls for security key presence and counter file integrity,
 * locking vaults if either the key is removed or the counter file is deleted.
 * @returns {$CancellablePromise<void>}
 */
export function StartDeviceWatcher() {
    return $Call.ByID(3906182605);
}

/**
 * StartIPCListener begins listening for IPC auth requests on a Unix socket.
 * @returns {$CancellablePromise<void>}
 */
export function StartIPCListener() {
    return $Call.ByID(1691723153);
}

/**
 * StopIPCListener shuts down the IPC listener and cleans up the socket.
 * @returns {$CancellablePromise<void>}
 */
export function StopIPCListener() {
    return $Call.ByID(1432751);
}

/**
 * Unlock performs FIDO2 assertion, unwraps the master secret, and decrypts all vaults.
 * @param {string} pin
 * @returns {$CancellablePromise<void>}
 */
export function Unlock(pin) {
    return $Call.ByID(1703829999, pin);
}

/**
 * UpdateSettings saves all settings to the HMAC-signed secure config.
 * All changes require a fresh FIDO2 assertion (PIN + touch).
 * @param {$models.CombinedSettings} settings
 * @param {string} pin
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSettings(settings, pin) {
    return $Call.ByID(3263880691, settings, pin);
}

/**
 * UpdateVaultMode changes the decrypt mode for a vault. Requires FIDO2 re-auth.
 * @param {string} path
 * @param {string} mode
 * @param {string} pin
 * @returns {$CancellablePromise<void>}
 */
export function UpdateVaultMode(path, mode, pin) {
    return $Call.ByID(1022512129, path, mode, pin);
}

// Private type creation functions
const $$createType0 = $models.DiskSpaceInfo.createFrom;
const $$createType1 = $models.UpdateInfo.createFrom;
const $$createType2 = $models.CombinedSettings.createFrom;
const $$createType3 = $models.AppStatus.createFrom;
const $$createType4 = $models.KeyInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
