// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddPath adds a folder or file to the protected list.
 */
export function AddPath(path: string, pin: string): $CancellablePromise<void> {
    return $Call.ByID(2105985761, path, pin);
}

/**
 * CancelIPCAuth is called when the user dismisses the IPC auth dialog.
 */
export function CancelIPCAuth(): $CancellablePromise<void> {
    return $Call.ByID(4237968635);
}

/**
 * CheckDiskSpace returns disk space info for a folder.
 */
export function CheckDiskSpace(path: string): $CancellablePromise<$models.DiskSpaceInfo> {
    return $Call.ByID(3312650982, path).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CheckForUpdate(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(3363528925).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DecryptLazyVault(path: string, pin: string): $CancellablePromise<void> {
    return $Call.ByID(2435244966, path, pin);
}

/**
 * DetectDevice checks if a FIDO2 device is connected.
 */
export function DetectDevice(): $CancellablePromise<boolean> {
    return $Call.ByID(948697146);
}

/**
 * EnterFullscreen switches the window to fullscreen for the lock screen.
 * If force authentication is enabled, activates kiosk mode.
 */
export function EnterFullscreen(): $CancellablePromise<void> {
    return $Call.ByID(2510957186);
}

/**
 * ExitFullscreen switches the window to normal mode after unlock.
 */
export function ExitFullscreen(): $CancellablePromise<void> {
    return $Call.ByID(4187733006);
}

/**
 * GetAdminGateCommand returns the terminal command the user should run to
 * install or remove the admin gate. Installs sudo PAM gate on all platforms
 * and the authorization plugin on macOS.
 */
export function GetAdminGateCommand(mode: string): $CancellablePromise<string> {
    return $Call.ByID(1430585252, mode);
}

/**
 * GetSettings returns settings from the secure config.
 */
export function GetSettings(): $CancellablePromise<$models.CombinedSettings> {
    return $Call.ByID(3129821644).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetStatus returns the current app state.
 */
export function GetStatus(): $CancellablePromise<$models.AppStatus> {
    return $Call.ByID(779018179).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(1806113387);
}

/**
 * HandleIPCAuth is called by the frontend after the user enters their PIN.
 */
export function HandleIPCAuth(pin: string): $CancellablePromise<void> {
    return $Call.ByID(1932996403, pin);
}

/**
 * HideToTray hides the window back to the system tray.
 * If the app is locked with force auth, re-enters fullscreen instead.
 */
export function HideToTray(): $CancellablePromise<void> {
    return $Call.ByID(4144683102);
}

export function IsLocked(): $CancellablePromise<boolean> {
    return $Call.ByID(1474303637);
}

export function IsRegistered(): $CancellablePromise<boolean> {
    return $Call.ByID(1771316975);
}

/**
 * ListKeys returns information about registered security keys.
 */
export function ListKeys(): $CancellablePromise<$models.KeyInfo[]> {
    return $Call.ByID(257323087).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Lock encrypts all vaults and clears secrets from memory.
 */
export function Lock(): $CancellablePromise<void> {
    return $Call.ByID(3911181120);
}

/**
 * LockVault re-encrypts a single vault on demand.
 */
export function LockVault(path: string): $CancellablePromise<void> {
    return $Call.ByID(3409273988, path);
}

/**
 * Register creates a new FIDO2 credential and wraps the master secret with it.
 * If this is the first credential, generates the master secret and hmac salt.
 * If credentials already exist, wraps the existing master secret with the new key.
 */
export function Register(pin: string, label: string): $CancellablePromise<void> {
    return $Call.ByID(2189947386, pin, label);
}

/**
 * RemoveFolder removes a folder from protection. Ensures files are decrypted first.
 * Requires FIDO2 re-auth.
 */
export function RemoveFolder(folderPath: string, pin: string): $CancellablePromise<void> {
    return $Call.ByID(205196671, folderPath, pin);
}

/**
 * RemoveKey removes a registered credential. Cannot remove the last key.
 * Requires FIDO2 re-auth.
 */
export function RemoveKey(credentialID: string, pin: string): $CancellablePromise<void> {
    return $Call.ByID(3195920610, credentialID, pin);
}

/**
 * ResizeWindow resizes the window to fit content.
 */
export function ResizeWindow(width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(1466929615, width, height);
}

/**
 * RevealSecureConfig opens the system file manager to the secure config directory.
 */
export function RevealSecureConfig(): $CancellablePromise<void> {
    return $Call.ByID(204196149);
}

export function SetWindow(w: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(541633429, w);
}

/**
 * StartDeviceWatcher polls for security key presence and counter file integrity,
 * locking vaults if either the key is removed or the counter file is deleted.
 */
export function StartDeviceWatcher(): $CancellablePromise<void> {
    return $Call.ByID(3906182605);
}

/**
 * StartIPCListener begins listening for IPC auth requests on a Unix socket.
 */
export function StartIPCListener(): $CancellablePromise<void> {
    return $Call.ByID(1691723153);
}

/**
 * StopIPCListener shuts down the IPC listener and cleans up the socket.
 */
export function StopIPCListener(): $CancellablePromise<void> {
    return $Call.ByID(1432751);
}

/**
 * Unlock performs FIDO2 assertion, unwraps the master secret, and decrypts all vaults.
 */
export function Unlock(pin: string): $CancellablePromise<void> {
    return $Call.ByID(1703829999, pin);
}

/**
 * UpdateSettings saves all settings to the HMAC-signed secure config.
 * All changes require a fresh FIDO2 assertion (PIN + touch).
 */
export function UpdateSettings(settings: $models.CombinedSettings, pin: string): $CancellablePromise<void> {
    return $Call.ByID(3263880691, settings, pin);
}

/**
 * UpdateVaultMode changes the decrypt mode for a vault. Requires FIDO2 re-auth.
 */
export function UpdateVaultMode(path: string, mode: string, pin: string): $CancellablePromise<void> {
    return $Call.ByID(1022512129, path, mode, pin);
}

// Private type creation functions
const $$createType0 = $models.DiskSpaceInfo.createFrom;
const $$createType1 = $models.UpdateInfo.createFrom;
const $$createType2 = $models.CombinedSettings.createFrom;
const $$createType3 = $models.AppStatus.createFrom;
const $$createType4 = $models.KeyInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
