// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppStatus {
    /**
     * Creates a new AppStatus instance.
     * @param {Partial<AppStatus>} [$$source = {}] - The source object to create the AppStatus.
     */
    constructor($$source = {}) {
        if (!("locked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["locked"] = false;
        }
        if (!("registered" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["registered"] = false;
        }
        if (!("vaults" in $$source)) {
            /**
             * @member
             * @type {VaultStatus[]}
             */
            this["vaults"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppStatus}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("vaults" in $$parsedSource) {
            $$parsedSource["vaults"] = $$createField2_0($$parsedSource["vaults"]);
        }
        return new AppStatus(/** @type {Partial<AppStatus>} */($$parsedSource));
    }
}

/**
 * CombinedSettings is the frontend-facing settings object.
 * All fields are stored in the HMAC-signed secure config.
 */
export class CombinedSettings {
    /**
     * Creates a new CombinedSettings instance.
     * @param {Partial<CombinedSettings>} [$$source = {}] - The source object to create the CombinedSettings.
     */
    constructor($$source = {}) {
        if (!("open_on_startup" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["open_on_startup"] = false;
        }
        if (!("force_authentication" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["force_authentication"] = false;
        }
        if (!("admin_gate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["admin_gate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CombinedSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CombinedSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CombinedSettings(/** @type {Partial<CombinedSettings>} */($$parsedSource));
    }
}

export class DiskSpaceInfo {
    /**
     * Creates a new DiskSpaceInfo instance.
     * @param {Partial<DiskSpaceInfo>} [$$source = {}] - The source object to create the DiskSpaceInfo.
     */
    constructor($$source = {}) {
        if (!("folder_gb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["folder_gb"] = 0;
        }
        if (!("free_gb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["free_gb"] = 0;
        }
        if (!("safe_to_migrate" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["safe_to_migrate"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiskSpaceInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiskSpaceInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiskSpaceInfo(/** @type {Partial<DiskSpaceInfo>} */($$parsedSource));
    }
}

export class KeyInfo {
    /**
     * Creates a new KeyInfo instance.
     * @param {Partial<KeyInfo>} [$$source = {}] - The source object to create the KeyInfo.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("credential_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["credential_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KeyInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeyInfo(/** @type {Partial<KeyInfo>} */($$parsedSource));
    }
}

export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("current_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current_version"] = "";
        }
        if (!("latest_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latest_version"] = "";
        }
        if (!("update_available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["update_available"] = false;
        }
        if (!("release_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["release_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}

export class VaultStatus {
    /**
     * Creates a new VaultStatus instance.
     * @param {Partial<VaultStatus>} [$$source = {}] - The source object to create the VaultStatus.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["type"] = undefined;
        }
        if (!("locked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["locked"] = false;
        }
        if (!("decrypt_mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["decrypt_mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VaultStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VaultStatus(/** @type {Partial<VaultStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = VaultStatus.createFrom;
const $$createType1 = $Create.Array($$createType0);
