// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as monban$0 from "./internal/monban/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddFile adds a single file to the protected list.
 */
export function AddFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(4103961850, path);
}

/**
 * AddFolder adds a folder to the protected list. Files are encrypted in place on lock.
 */
export function AddFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(2264495576, path);
}

/**
 * CheckDiskSpace returns disk space info for a folder.
 */
export function CheckDiskSpace(path: string): $CancellablePromise<$models.DiskSpaceInfo> {
    return $Call.ByID(2200595672, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DetectDevice checks if a FIDO2 device is connected.
 */
export function DetectDevice(): $CancellablePromise<boolean> {
    return $Call.ByID(1302359116);
}

/**
 * EnterFullscreen switches the window to fullscreen for the lock screen.
 * If force authentication is enabled, activates kiosk mode.
 */
export function EnterFullscreen(): $CancellablePromise<void> {
    return $Call.ByID(2979408584);
}

/**
 * ExitFullscreen switches the window to normal mode after unlock.
 */
export function ExitFullscreen(): $CancellablePromise<void> {
    return $Call.ByID(3924053808);
}

/**
 * GetSettings returns the current settings.
 */
export function GetSettings(): $CancellablePromise<monban$0.Settings> {
    return $Call.ByID(2554697378).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetStatus returns the current app state.
 */
export function GetStatus(): $CancellablePromise<$models.AppStatus> {
    return $Call.ByID(1043986649).then(($result: any) => {
        return $$createType2($result);
    });
}

export function IsLocked(): $CancellablePromise<boolean> {
    return $Call.ByID(3297540203);
}

export function IsRegistered(): $CancellablePromise<boolean> {
    return $Call.ByID(1802140665);
}

/**
 * ListKeys returns information about registered YubiKeys.
 */
export function ListKeys(): $CancellablePromise<$models.KeyInfo[]> {
    return $Call.ByID(1130532105).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Lock encrypts all vaults and clears secrets from memory.
 */
export function Lock(): $CancellablePromise<void> {
    return $Call.ByID(253832250);
}

/**
 * Register creates a new FIDO2 credential and initializes the config.
 * If this is the first credential, generates the master secret and hmac salt.
 * If credentials already exist, wraps the existing master secret with the new key.
 */
export function Register(pin: string, label: string): $CancellablePromise<void> {
    return $Call.ByID(147219160, pin, label);
}

/**
 * RemoveFolder removes a folder from protection. Ensures files are decrypted first.
 */
export function RemoveFolder(folderPath: string): $CancellablePromise<void> {
    return $Call.ByID(58441789, folderPath);
}

/**
 * RemoveKey removes a registered credential. Cannot remove the last key.
 */
export function RemoveKey(credentialID: string): $CancellablePromise<void> {
    return $Call.ByID(2578636620, credentialID);
}

/**
 * ResizeWindow resizes the window to fit content.
 */
export function ResizeWindow(width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(2916372761, width, height);
}

export function SetWindow(w: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(3654517795, w);
}

/**
 * StartDeviceWatcher polls for YubiKey presence and locks when removed.
 */
export function StartDeviceWatcher(): $CancellablePromise<void> {
    return $Call.ByID(1189108695);
}

/**
 * Unlock performs FIDO2 assertion, unwraps the master secret, and decrypts all vaults.
 */
export function Unlock(pin: string): $CancellablePromise<void> {
    return $Call.ByID(1127700317, pin);
}

/**
 * UpdateSettings saves settings to config and applies side effects.
 */
export function UpdateSettings(settings: monban$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(2894041249, settings);
}

// Private type creation functions
const $$createType0 = $models.DiskSpaceInfo.createFrom;
const $$createType1 = monban$0.Settings.createFrom;
const $$createType2 = $models.AppStatus.createFrom;
const $$createType3 = $models.KeyInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
