// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddFolder adds a folder to the protected list. Files are encrypted in place on lock.
 */
export function AddPath(path: string, pin: string): $CancellablePromise<void> {
    return $Call.ByID(2553945579, path, pin);
}

/**
 * CheckDiskSpace returns disk space info for a folder.
 */
export function CheckDiskSpace(path: string): $CancellablePromise<$models.DiskSpaceInfo> {
    return $Call.ByID(2200595672, path).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CheckForUpdate(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(2347956003).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DecryptLazyVault(path: string, pin: string): $CancellablePromise<void> {
    return $Call.ByID(2513125692, path, pin);
}

/**
 * DetectDevice checks if a FIDO2 device is connected.
 */
export function DetectDevice(): $CancellablePromise<boolean> {
    return $Call.ByID(1302359116);
}

/**
 * EnterFullscreen switches the window to fullscreen for the lock screen.
 * If force authentication is enabled, activates kiosk mode.
 */
export function EnterFullscreen(): $CancellablePromise<void> {
    return $Call.ByID(2979408584);
}

/**
 * ExitFullscreen switches the window to normal mode after unlock.
 */
export function ExitFullscreen(): $CancellablePromise<void> {
    return $Call.ByID(3924053808);
}

/**
 * GetSettings returns settings from the secure config.
 */
export function GetSettings(): $CancellablePromise<$models.CombinedSettings> {
    return $Call.ByID(2554697378).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetStatus returns the current app state.
 */
export function GetStatus(): $CancellablePromise<$models.AppStatus> {
    return $Call.ByID(1043986649).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetSudoGateCommand returns the terminal command the user should run to
 * install or remove the sudo gate PAM config. On macOS Tahoe+, /etc/pam.d/
 * is TCC-protected and can only be written from Terminal with sudo.
 */
export function GetSudoGateCommand(mode: string): $CancellablePromise<string> {
    return $Call.ByID(2404724622, mode);
}

export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(1049863377);
}

export function IsLocked(): $CancellablePromise<boolean> {
    return $Call.ByID(3297540203);
}

export function IsRegistered(): $CancellablePromise<boolean> {
    return $Call.ByID(1802140665);
}

/**
 * ListKeys returns information about registered security keys.
 */
export function ListKeys(): $CancellablePromise<$models.KeyInfo[]> {
    return $Call.ByID(1130532105).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Lock encrypts all vaults and clears secrets from memory.
 */
export function Lock(): $CancellablePromise<void> {
    return $Call.ByID(253832250);
}

/**
 * LockVault re-encrypts a single vault on demand.
 */
export function LockVault(path: string): $CancellablePromise<void> {
    return $Call.ByID(563136070, path);
}

/**
 * Register creates a new FIDO2 credential and wraps the master secret with it.
 * If this is the first credential, generates the master secret and hmac salt.
 * If credentials already exist, wraps the existing master secret with the new key.
 */
export function Register(pin: string, label: string): $CancellablePromise<void> {
    return $Call.ByID(147219160, pin, label);
}

/**
 * RemoveFolder removes a folder from protection. Ensures files are decrypted first.
 * Requires FIDO2 re-auth.
 */
export function RemoveFolder(folderPath: string, pin: string): $CancellablePromise<void> {
    return $Call.ByID(58441789, folderPath, pin);
}

/**
 * RemoveKey removes a registered credential. Cannot remove the last key.
 * Requires FIDO2 re-auth.
 */
export function RemoveKey(credentialID: string, pin: string): $CancellablePromise<void> {
    return $Call.ByID(2578636620, credentialID, pin);
}

/**
 * ResizeWindow resizes the window to fit content.
 */
export function ResizeWindow(width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(2916372761, width, height);
}

/**
 * RevealSecureConfig opens the system file manager to the secure config directory.
 */
export function RevealSecureConfig(): $CancellablePromise<void> {
    return $Call.ByID(752810371);
}

export function SetWindow(w: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(3654517795, w);
}

/**
 * StartDeviceWatcher polls for security key presence and counter file integrity,
 * locking vaults if either the key is removed or the counter file is deleted.
 */
export function StartDeviceWatcher(): $CancellablePromise<void> {
    return $Call.ByID(1189108695);
}

/**
 * Unlock performs FIDO2 assertion, unwraps the master secret, and decrypts all vaults.
 */
export function Unlock(pin: string): $CancellablePromise<void> {
    return $Call.ByID(1127700317, pin);
}

/**
 * UpdateSettings saves all settings to the HMAC-signed secure config.
 * All changes require a fresh FIDO2 assertion (PIN + touch).
 */
export function UpdateSettings(settings: $models.CombinedSettings, pin: string): $CancellablePromise<void> {
    return $Call.ByID(2894041249, settings, pin);
}

/**
 * UpdateVaultMode changes the decrypt mode for a vault. Requires FIDO2 re-auth.
 */
export function UpdateVaultMode(path: string, mode: string, pin: string): $CancellablePromise<void> {
    return $Call.ByID(1049583931, path, mode, pin);
}

// Private type creation functions
const $$createType0 = $models.DiskSpaceInfo.createFrom;
const $$createType1 = $models.UpdateInfo.createFrom;
const $$createType2 = $models.CombinedSettings.createFrom;
const $$createType3 = $models.AppStatus.createFrom;
const $$createType4 = $models.KeyInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
