// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppStatus {
    "locked": boolean;
    "registered": boolean;
    "vaults": VaultStatus[];

    /** Creates a new AppStatus instance. */
    constructor($$source: Partial<AppStatus> = {}) {
        if (!("locked" in $$source)) {
            this["locked"] = false;
        }
        if (!("registered" in $$source)) {
            this["registered"] = false;
        }
        if (!("vaults" in $$source)) {
            this["vaults"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): AppStatus {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("vaults" in $$parsedSource) {
            $$parsedSource["vaults"] = $$createField2_0($$parsedSource["vaults"]);
        }
        return new AppStatus($$parsedSource as Partial<AppStatus>);
    }
}

/**
 * CombinedSettings is the frontend-facing settings object that merges
 * fields from both user config and secure config.
 */
export class CombinedSettings {
    "open_on_startup": boolean;
    "force_authentication": boolean;
    "sudo_gate": string;

    /** Creates a new CombinedSettings instance. */
    constructor($$source: Partial<CombinedSettings> = {}) {
        if (!("open_on_startup" in $$source)) {
            this["open_on_startup"] = false;
        }
        if (!("force_authentication" in $$source)) {
            this["force_authentication"] = false;
        }
        if (!("sudo_gate" in $$source)) {
            this["sudo_gate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CombinedSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): CombinedSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CombinedSettings($$parsedSource as Partial<CombinedSettings>);
    }
}

export class DiskSpaceInfo {
    "folder_gb": number;
    "free_gb": number;
    "safe_to_migrate": boolean;

    /** Creates a new DiskSpaceInfo instance. */
    constructor($$source: Partial<DiskSpaceInfo> = {}) {
        if (!("folder_gb" in $$source)) {
            this["folder_gb"] = 0;
        }
        if (!("free_gb" in $$source)) {
            this["free_gb"] = 0;
        }
        if (!("safe_to_migrate" in $$source)) {
            this["safe_to_migrate"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiskSpaceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DiskSpaceInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiskSpaceInfo($$parsedSource as Partial<DiskSpaceInfo>);
    }
}

export class KeyInfo {
    "label": string;
    "credential_id": string;

    /** Creates a new KeyInfo instance. */
    constructor($$source: Partial<KeyInfo> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("credential_id" in $$source)) {
            this["credential_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): KeyInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeyInfo($$parsedSource as Partial<KeyInfo>);
    }
}

export class UpdateInfo {
    "current_version": string;
    "latest_version": string;
    "update_available": boolean;
    "release_url": string;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("current_version" in $$source)) {
            this["current_version"] = "";
        }
        if (!("latest_version" in $$source)) {
            this["latest_version"] = "";
        }
        if (!("update_available" in $$source)) {
            this["update_available"] = false;
        }
        if (!("release_url" in $$source)) {
            this["release_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

export class VaultStatus {
    "label": string;
    "path": string;
    "type"?: string;
    "locked": boolean;

    /** Creates a new VaultStatus instance. */
    constructor($$source: Partial<VaultStatus> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("locked" in $$source)) {
            this["locked"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): VaultStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VaultStatus($$parsedSource as Partial<VaultStatus>);
    }
}

// Private type creation functions
const $$createType0 = VaultStatus.createFrom;
const $$createType1 = $Create.Array($$createType0);
