// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class IPCRequest {
    /**
     * "auth"
     */
    "type": string;

    /**
     * invoking user
     */
    "user": string;

    /**
     * PAM service (e.g. "sudo", "authorization")
     */
    "service": string;

    /** Creates a new IPCRequest instance. */
    constructor($$source: Partial<IPCRequest> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("service" in $$source)) {
            this["service"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPCRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): IPCRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IPCRequest($$parsedSource as Partial<IPCRequest>);
    }
}
