// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PluginStatus is a read-only snapshot of a loaded plugin for UI/API use.
 */
export class PluginStatus {
    "name": string;
    "version": string;
    "kind": string[];
    "hooks"?: string[];
    "dir": string;
    "loaded": boolean;

    /** Creates a new PluginStatus instance. */
    constructor($$source: Partial<PluginStatus> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = [];
        }
        if (!("dir" in $$source)) {
            this["dir"] = "";
        }
        if (!("loaded" in $$source)) {
            this["loaded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginStatus {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("kind" in $$parsedSource) {
            $$parsedSource["kind"] = $$createField2_0($$parsedSource["kind"]);
        }
        if ("hooks" in $$parsedSource) {
            $$parsedSource["hooks"] = $$createField3_0($$parsedSource["hooks"]);
        }
        return new PluginStatus($$parsedSource as Partial<PluginStatus>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
